default: &default
  adapter: mysql2
  username: root
  password: 1
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: northern_development

test:
  <<: *default
  database: northern_test

production:
  adapter: postgresql
  database: northern_production
  host: localhost
  password:
